### ISSUE TITLE
24/03/09

### ISSUE THREAD

**Issue by yukudaa** [Strongest-Engineer/Interview#1]
**HTTP의 GET과 POST 비교**
- CORS문제를 해결하는 방법과 브라우저에서 CORS가 발생하는 이유
- 쿠키, 캐시, 세션의 개념과 차이점
- http 상태코드의 예시와 각 상태 코드별 나타날 수 있는 예시 설명

**Comment by SeonJuuuun** [comment]
- CORS문제를 해결하는 방법과 브라우저에서 CORS가 발생하는 이유
    
    브라우저에서 CORS가 발생하는 이유
    
    일단 CORS는 서로 다른 출처(Origin) 간에 리소스를 전달하는 방식을 제어하는 체제
    
    CORS 요청이 가능하려면 서버에서 특정 헤더인 Access-Control-Allow-Origin과 함께 응답할 필요가 있다.
    
    즉, CORS 정책을 위반하여 서로 다른 출처를 가진 상태에서 무언가를 요청하게 되면 브라우저가 보안 상의 이유로 차단을 한다.
    
    CORS 문제를 해결하려면 동일한 출처에서 리소스를 요청하면 된다.
    
    가장 대표적인 방법은, 그냥 정석대로 서버에서 **Access-Control-Allow-Origin** 헤더에 알맞은 값을 세팅해주는 것이다.
    
    즉, [https://evan.github.io의](https://evan.github.xn--io-jx8j/) 출처를 **`Access-Control-Allow-Origin: https://evan.github.io`**와 같이 출처를 명시해주면 된다.
    
    webpack-dev-server의 프록싱 옵션을 사용해서 자체적으로 해결하는 방법도 있긴 하지만, 로컬 개발 환경에서만 통하는 방법이며, 근본적인 해결방법이 아니다.
    

- 쿠키, 캐시, 세션의 개념과 차이점
    
    쿠키 :
    
    사용자 브라우저에 저장되고, 통신할 때 http 헤더에 포함되는 텍스트 데이터 파일 ⇒ 해당 사용자의 컴퓨터를 사용한다면 누구나 쿠키에 입력된 값을 쉽게 사용 가능 → 보안성이 낮다. ex) 자동 로그인 유지, 위시 리스트 저정, 팝업 보지 않기, 사용자 이전 스크롤링이나 뷰 설정 값
    
    쿠키 통신 방법
    
    (1) 최초 통신에서는 쿠키값이 없으므로, 일단 클라이언트는 Request 를 한다.
    
    (2) 서버에서 클라이언트가 보낸 Request Header에 쿠키가 없음을 판별.    통신 상태(UserID, Password, 조작상태, 방문횟수 등)를 저장한 쿠키를 Response한다.
    
    (3) 클라이언트의 브라우저가 받은 쿠키를 생성/보존한다
    
    (4) 두번째 연결부턴, HTTP Header에 쿠키를 실어서 서버에 Request 한다
    
    세션 :
    
    쿠키와 달리 사용자 로컬이 아닌 서버에 직접 저장되므로, 세션 내에 데이터를 탈취하는 것은 어려움 → 보안성이 비교적 높음
    
    세션 통신 방법
    
    (1) 클라이언트가 서버에 접속 시, 세션 ID를 발급한다.
    
    (2) 서버에서는 클라이언트로 발급해준 세션 ID를 쿠키를 이용해서 저장
    
    (3) 클라이언트는 다시 페이지에 접속할 때, 쿠키에 저장된 세션 ID를 서버에 전달
    
    (4) 서버는 Request Header에 쿠키 정보(세션 ID)로 클라이언트를 판별
    
    ex) 로그인 정보 유지
    
    캐시 : 
    
    리소스 파일들의 임시 저장소. 같은 웹 페이지에 접속할 때 사용자의 PC에서 로드하므로 서버를 거치지 않아도 된다.이전에 사용되었던 데이터는 다시 사용될 가능성이 높다 -> 그래서 다시 사용될 확률이 있는 데이터들을 빠르게 접근 가능한 저장소에 저장한다.=> 페이지 로딩 속도를 개선함이미지, 비디오 오디오, CSS/JS 등...
    
- http 상태코드의 예시와 각 상태 코드별 나타날 수 있는 예시 설명
    
    200 OK : 
    
    대표적인 성공코드, 에러 없이 요청이 성공적으로 진행되었다.
    
    201 Created :
    
    요청이 성공적으로 처리 되어서 새로운 리소스가 생성되었을 때 사용하는 코드
    
    POST, PUT등의 요청에 대한 응답으로 주로 사용됨
    
    204 No Content : 
    
    요청이 성공적으로 처리 되었지만, 제공 해줄 응답 데이터가 없을 때 204를 사용한다. 예를들어, PUT으로 수정 요청을 받았는데 수정할 사항이 없는 경우,
    
    요청은 성공했으니 200번대 코드를 사용하지만 응답할 데이터도 없으므로 204를 사용한다, delete도 마찬가지다.
    
    301 Moved Permanently :
    
    요청한 리소스가 응답 헤더에 Location에 주어진 URL로 완전히 옮겨졌음을 의미. 예를들어 주소창에 [http://naver.com/을](http://naver.com/%EC%9D%84) 입력하면 301을 리턴하는데 응답 헤더에 Location을 확인해보면 [http://www.naver.com/으로](http://www.naver.com/%EC%9C%BC%EB%A1%9C) 리다이렉션 된다.
    
    302 Found : 
    
    301과 비슷하게 사용되는데 301의 경우는 영구적 302는 일시적으로 이동한다.
    
    400 Bad Request
    
    API에 정의되지 않은 방식으로 요청하거나 클라이언트가 잘못된 요청을 했을 때 사용한다. 예를 들어 로그인 할 때 id만 보내고 password를 보내지 않았을 때 400사용가능
    
    401 Unauthorized / 403 Forbidden
    
    두 경우 모두 권한이 없어서 요청을 받아들일 수 없을 때 사용한다.
    
    401은 인증이 되지 않은 경우 ⇒ 로그인이 필요한 기능을 로그인 하지 않은 상태
    
    403은 권한이 없는 경우 ⇒ 네이버 카페에서 로그인은 되었지만 등급 제한이 걸려있어 접속 권한이 없을 경우

**Comment by yukudaa** [comment]
- CORS문제를 해결하는 방법과 브라우저에서 CORS가 발생하는 이유

Cross-Origin Resource Sharing (다른 출처에서 리소스 공유 정책)

Origin: Protocol + Host + Post
Origin이 동일하다면 동일 출처로 판단

동일 출처 정책이 필요한 경우
사실 출처가 다른 두 어플리케이션이 자유로이 소통할 수 있는 환경은 꽤 위험한 환경이다. 만일 제약이 없다면, 해커가 CSRF(Cross-Site Request Forgery)나 XSS(Cross-Site Scripting) 등의 방법을 이용해서 우리가 만든 어플리케이션에서 해커가 심어놓은 코드가 실행하여 개인 정보를 가로챌 수 있다

해결하는 방법
Chrome 확장 프로그램 이용: Allow CORS: Access-Control-Allow-Origin' 크롬 확장 프로그램을을 설치 -> 해당 프로그램을 활성화 시키게 되면, 로컬(localhost) 환경에서 API를 테스트 시, CORS 문제를 해결할 수 있다.

- 쿠키, 캐시, 세션의 개념과 차이점

쿠키: HTTP통신은 stateless 하기 때문에 클라이언트를 확인하기 위해서는 쿠키라는 개념이 필요, 주로 세션관리(서버에서 관리하는 로그인 등의 정보를 의미), 개인 설정유지, 사용자 트래킹(사용자의 행동을 기록하고 분석하는 것) 용도로 사용

```
쿠키도 결국 HTTP 통신에서 이루어지는 것이기 때문에 HTTP 의 응답과 요청에 따라 작동한다.요청을 받은 서버에서 쿠키를 클라이언트(웹 브라우저)로 보내고 클라이언트는 쿠키를 받으면 도메인 서버 이름으로 정렬된 쿠키 디렉토리에 쿠키(정보)를 저장한다. 이후 클라이언트가 동일한 서버로 HTTP 요청을 보내면 저장된 쿠키도 같이 전송되며, 만약 서버에서 쿠키에 업데이트된 내용이 있으면 응답할 때 다시 업데이트된 쿠키를 보내준다.< 쿠키 작동순서 >
```
!https://blog.kakaocdn.net/dn/pf1N6/btqv8ZCLXgy/cHTFZxnBa2mOw8wPGf6pM0/img.png

세션: 통신을 하기 위해 서로 연결된 순간부터 통신을 마칠때까지의 기간

```
서버에 세션에 대한 정보(세션 상태, 클라이언트 상태, 세션 데이터 등)를 저장해 놓고 세션 쿠키( 고유한 세션 ID 값 )를 클라이언트에게 주어 서버가 클라이언트를 식별할 수 있도록 하는 방식자체를 의미하는 경우가 많다.
```

```
세션의 작동방식을 보면 우선 클라이언트가 서버에 요청을 보내면 서버에서는 요청헤더( Cookie )를 확인하고 세션 ID가 있는지 확인한다. 만약 요청에 세션 ID가 없다면 서버에서는 세션 ID를 생성한 뒤 응답을 보낼 때 쿠키에 세션 ID를 담아 보낸다. (서버에서는 이때 가장 먼저 세션 객체를 생성하여 정보를 저장한다.)클라이언트는 응답에서 받은 세션 쿠키(세션 ID 값)를 저장해두고, 매번 해당 서버에 요청을 보낼 때마다 세션 쿠키를 함께 보내서 자신이 누구인지 인증한다. 세션 쿠키는 브라우저가 종료되면 삭제된다.
```

!https://blog.kakaocdn.net/dn/vaGpm/btqv8md80Kr/PXhH7cgDMNpl6lhmKeriSK/img.png

```
쿠키와 세션을 비교할 때 쿠키는 클라이언트(웹 브라우저)에 정보를 저장하는 것이고, 세션은 서버에 정보를 저장하는 것이다 라고 비교한다. 맞는 말이지만 마치 서로 반대되는 개념처럼 오해할 수 있는데, 결국 세션은 쿠키를 이용하는 하나의 방식일 뿐
```

캐시: 캐시(Cache)는 사용자가 웹사이트나 앱에서 서비스를 이용하는 과정에서 이미지, HTML, 파일과 같이 재사용할 수 있는 이전에 사용되었던 데이터들이 보관되는 저장 공간이다. 서버에 재요청할 때 캐시를 이용하면 더 빠르게 이용할 수 있다. 캐시는 컴퓨터의 성능을 향상시키기 위해서 사용되는 고속 기억 장치이며 주기억장치의 일부분이다.

중앙처리장치(CPU)와 중앙처리장치에 비해서 속도가 느린 주기억장치 사이에서 데이터와 명령어들을 일시적으로 저장하는 메모리를 제공한다. 캐시는 컴퓨터 CPU, 웹, 앱, 서버와 같이 다양한 영역에 사용된다. 캐시를 사용하면 사용자가 웹사이트와 앱에 처음 접속한 이후 다시 접속할 때 더 빠르게 사용할 수 있게 해준다.

- http 상태코드의 예시와 각 상태 코드별 나타날 수 있는 예시 설명

1xx (Informatinal): 요청이 수신되어 처리중

2xx (Successful): 요청 정상 처리

3xx (Redirection): 요청이 완료되려면 추가 행동이 필요

4xx (Client Error): 클라이언트 오류, 잘못된 문법등으로 서버가 요청을 수행할 수 없음

5xx (Server Error): 서버 오류, 서버가 정상 요청을 처리하지 못함

200 OK 요청 성공

201 Created 요청 성공해서 새로운 리소스가 생성됨

301 Moved Permanently 리다이렉트시 요청 메서드가 GET으로 변하고, 본문이 제거될 수 있음

400 Bad Request 클라이언트가 잘못된 요청을 해서 서버가 요청을 처리할 수 없음

401 Unauthorized 클라이언트가 해당 리소스에 대한 인증이 필요함

404 Not Found 요청 리소스를 찾을 수 없음

500 Internal Server Error 서버 문제로 오류 발생

503 Service Unavailable 서비스 이용 불가

**Comment by jinft-kr** [comment]
1. CORS문제를 해결하는 방법과 브라우저에서 CORS가 발생하는 이유
CORS(Cross-Origin Resource Sharing)는 웹 브라우저에서 실행되는 스크립트가 다른 출처(Origin)에서 리소스에 접근할 수 있는 보안 메커니즘이다. 다른 출처의 리소스에 대한 접근은 보안상의 이유로 기본적으로 차단된다.

- 문제 상황이 발생하는 경우
(1) 다른 도메인에서 AJAX 요청을 보낼 때: 웹 애플리케이션에서 다른 도메인의 API에 AJAX 요청을 보내는 경우, 브라우저는 보안 상의 이유로 이를 차단할 수 있다. 예를 들어, 웹 애플리케이션이 http://example.com에 호스팅되어 있는데, AJAX 요청을 사용하여 http://api.example.net에 있는 API에 접근하는 경우 브라우저는 CORS 정책에 따라 이를 차단할 수 있다.
(2) Cross-Origin 리소스에 접근할 때: 웹 페이지에서 <img>, <script>, <link>, <iframe> 등과 같은 리소스를 로드하는 경우에도 CORS 오류가 발생할 수 있다. 예를 들어, 웹 페이지가 http://example.com에 있고, <img> 태그를 사용하여 http://api.example.net/image.jpg를 로드하는 경우 브라우저는 이를 차단할 수 있다.
(3) 쿠키를 사용하여 인증하는 경우: 보안상의 이유로 브라우저는 다른 출처의 쿠키에 접근하는 것을 제한한다. 따라서 다른 출처에서 보낸 AJAX 요청에 인증된 사용자의 쿠키를 포함하는 경우, 브라우저는 CORS 오류를 발생시킬 수 있다.

- 해결하는 방법
(1) 서버 측 설정 변경: 서버에서는 응답 헤더를 설정하여 CORS를 허용할 출처를 명시할 수 있다. 이를 위해서는 Access-Control-Allow-Origin 헤더를 적절하게 설정한다. 예를 들어, 모든 출처에서의 요청을 허용하려면 "*"를 사용할 수 있다. 또는 특정 출처만 허용하려면 해당 출처를 명시한다.

(2)프록시 서버 사용: 프록시 서버를 사용하여 클라이언트 측 요청을 서버 측으로 전달하고 응답을 반환하는 방법을 사용할 수 있다. 이는 클라이언트가 직접 서버에 요청을 보내는 것이 아니므로 Same-Origin Policy에 해당하지 않는다.
예) http://example.com -> http://api.example.com 요청할 때, http://example.com -> http://example-proxy.com -> http://api.example.com 와 같이 프록시하여 요청 전송

2. 쿠키, 캐시, 세션의 개념과 차이점
(1) 쿠키 (Cookies)
- 쿠키 생명주기
   - Set-Cookie : expires-Satm 26-Dec-2020 04L39L21 GMT
      - 만료일이되면 쿠키 삭제
   - Set-Cokkie : max-age=3600(3600초)
      - 0이나 음수를 지정하면 쿠키 삭제
   - 세션 쿠키: 만료 날짜를 생략하면 브라우저 종료시까지만 유지
   - 영속 쿠키 : 만료 날짜를 입력하면 해당 날짜까지 유지
     
- 사용처 : 사용자 로그인 세션 관리, 광고 정보 트래킹

- 사용자의 브라우저에 저장되고, 통신할 때 HTTP헤더에 포함하여 항상 서버에 전송된다.

- 쿠키 통신 방법
(1) 최초 통신에서는 쿠키값이 없으므로, 일단 클라이언트는 요청 한다.
(2) 서버에서 클라이언트가 보낸 Request Header에 쿠키가 없음을 판별하고, 통신 상태를 저장한 쿠키를 Response한다.(Header의 Set-Cookie에 저장)
(3) 클라이언트의 브라우저가 받은 쿠키를 브라우저내 쿠키저장소에 저장한다.
(4) 두번째 연결부턴, 모든 요청에 쿠키정보를 자동으로 포함하여 HTTP Header(Cookie)에 쿠키를 실어서 서버에 요청 한다
   - 이로인해 네트워크 트래픽 추가비용을 유발한다.
- 쿠키는 클라이언트와 서버 간의 상태를 유지하는 데 사용되며, 만료 날짜를 설정하여 영구적인 쿠키 또는 세션 종료 시 삭제되는 세션 쿠키가 있다.

(2) 캐시 (Cache):
- 캐시 : 이전에 요청된 데이터의 사본을 저장하는 임시 저장소(ex: 브라우저 캐시)

- 사용처 : 주로 웹 페이지의 로딩 속도를 향상시키기 위해 사용 이전에 요청된 데이터를 다시 요청하지 않고 저장된 사본을 사용하여 성능을 향상 시킴.

- 캐시 동작 원리
(1) 최초 API 요청시 Request를 보냄
(2) 응답시 헤더에 cache-control(캐시가 유효한 시간)을 받음
(3) 캐시 데이터를 브라우저 캐시에 저장.
(3) 두번째 요청부터는 캐시 유효시간 검증 후 유효하다면 서버로 부터 응답을 받지 않고 캐시에서 응답을 보내줌
(4) 캐시 시간 초과시 서버로 API를 요청
(5) API에서 데이터를 응답받고, 캐시를 갱신함
    - API로 부터 응답받은 데이터에 업데이트가 생겨 캐시데이터를 사용하지 않고 다시 조회를 해야하는 경우 검증 헤더를 통해 캐시 데이터를 업데이트할 수 있다.

(3)세션 (Session):
- 세션 : 클라이언트와 서버 간의 상태 정보를 유지하기 위한 메커니즘

- 세션은 서버 측에서 유지되며, 클라이언트는 세션 식별자를 받아서 이를 통해 세션에 대한 상태 정보에 접근합니다.
- 서버에 데이터가 저장되기 때문에 보안성이 높다.

- 세션 통신 방법
(1) 클라이언트가 서버에 접속 시, 서버는 해당 세션에 대한 고유한 세션 ID를 생성
(2) 서버에서는 클라이언트로 발급해준 세션 ID를 쿠키 등을 통해 클라이언트에게 전달한다. 쿠키로 전달시 사용자 브라우저에 저장.
(3) 클라이언트는 다시 페이지에 접속할 때, 쿠키에 저장된 세션 ID를 서버에 전달
(4) 서버는 Request Header에 쿠키 정보(세션 ID)로 클라이언트를 판별

(4)차이점:
- 쿠키는 클라이언트 측에서 저장되고, 캐시와 세션은 서버 측에서 관리됨
- 쿠키는 클라이언트와 서버 간의 상태를 유지하는 데 사용되고, 캐시는 이전에 요청된 데이터의 사본을 저장하여 성능을 향상시키는 데 사용됨
- 세션은 일시적인 사용자 상태를 유지하고 사용자를 식별하기 위해 사용되며, 세션은 주로 사용자 로그인 정보 및 상태 정보를 저장하는 데 사용됩니다.

3. http 상태코드의 예시와 각 상태 코드별 나타날 수 있는 예시 설명
- HTTP 상태코드란 : 클라이언트가 보낸 요청의 처리 상태를 알려주는 기능
- 상태코드의 종류
(1) 1xx(Informational) : 요청이 수신되어 처리중

(2) 2xx(Successful): 요청 정상 처리
- 201(Created) : 클라이언트 요청으로 부터 서버에서 무언가 리소스를 생성(ex: POST 요청)
- 202(Accepted) : 요청이 접수되었으나 처리가 완료되지 않았음(ex: 배치 처리 같은 곳에서 사용, 요청 접수 후 1시간 뒤에 배치 프로세스가 요청을 처리함)
- 204(No Content) : 서버가 요청을 성공적으로 수행했지만, 응답 페이로드 본문에 보낼 데이터가 없음(ex: 버튼 클릭 이후 응답 결과로 아무 내용이 없어도 되는 경우)

(3) 3xx(Redirection) : 요청을 완료하려면 유저 에이전트의 추가 행동이 필요
- 영구 리다이렉션(301,308), 일시적인 리다이렉션(302, 303, 307, 기타 리다이렉션(300, 304)), 
- 301(Moved Permanently) : 리다이렉트시 요청 메서드가 GET으로 변하고, 본문이 제거될 수 있음(ex : 이벤트 페이지를 리다이렉트하는데 새로고침하는 경우 기존 입력한 내용 모두 사라짐)
- 304(Not Modified) : 캐시를 목적으로 사용. 클라이언트에게 리소스가 수정되지 않았음을 알려줌. 따라서 클라이언트는 로컬 PC에 저장된 캐시를 재사용. (ex: 브라우저에서 특정경로를 통해 다운 받아진 이미지가 캐시에 저장되어 있는데, 재 요청하는 경우 캐시로 리다이렉트 함)
- 308(Permanent Redirect) : 리다이렉트 요청 메서드와 본문 유지(처음 POST를 보내면 리다이렉트도 POST)

(4) 4xx(Client Error) : 클라이언트 오류, 잘못된 문법 등으로 서버가 요청을 수행할 수 없음
- 400(Bad Request) : 클라이언트가 잘못된 요청을 해서 서버가 요청을 처리할 수 없음(ex: 요청 파라미터가 잘못되거나 API 스펙이 맞지 않을 때)
- 401(Unauthorized) : 클라이언트가 해당 리소스에 대한 인증이 되지 않음(ex: 로그인시 인증이 되지 않았을 때)
(참고)
- 403(Forbidden) : 서버가 요청을 이해했지만 승인을 거부함(ex: 인증 자격은 있지만 접근 권한이 불충분할 때)
  - 인증(Authentication) : 본인이 누구인지 확인,(로그인)
  - 인가(Authorization) : 권한 부여(ADMIN 권한 처럼 특정 리소스에 접근할 수 있는 권한, 인증이 있어야 인가가 있음) 
- 404(Not Found) : 요청 리소스를 찾을 수 없음(ex:리소스를 찾을 수 없거나 클라이언트가 권한이 부족한 리소스에 접근 할 때 해당 리소스를 숨기고 싶을 때)

(5) 5xx(Sever Error) : 서버 오류, 서버가 정상 요청을 처리하지 못함
- 500(Internal Server Error) : 서버 문제로 오류 발생(ex: 서버의 데이터 베이스에 문제가 생긴 경우)
- 503(Service Unavailable) : 서비스 이용 불가(ex: 서버가 일시적으로 과부하가 걸리거나 예정된 작업으로 잠시 요청을 처리할 수 없을 때)
